[package]
name = "verbs-game"
version = "0.1.0"
authors = ["ozel-byte <ozelcode@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
random-number = "0.1.6"
